/* Generated by config/generate.py. Do not edit. */
#pragma once
#include <stdint.h>

static inline uint32_t esp_gsp_required_glyph_run_slots(
        uint32_t text_slots, uint32_t list_count,
        uint32_t list_max_slots, uint32_t list_text_slots)
{
    uint64_t value = (uint64_t)text_slots +
        (uint64_t)list_count * list_max_slots * list_text_slots + 2U;
    return value <= UINT32_MAX ? (uint32_t)value : UINT32_MAX;
}
