/* Generated by config/generate.py. Do not edit. */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ESP_GSP_CONFIG_SCHEMA_VERSION 2U
#define ESP_GSP_CONFIG_ABI_VERSION 3U
#define ESP_GSP_CONFIG_FIELD_COUNT 94U
#define ESP_GSP_CONFIG_INLINE_OVERRIDES 8U

typedef enum {
    ESP_GSP_FIELD_MAX_SCENES = 0,
    ESP_GSP_FIELD_MAX_TIMERS = 1,
    ESP_GSP_FIELD_MAX_WIDGETS = 2,
    ESP_GSP_FIELD_MAX_ANIMATIONS = 3,
    ESP_GSP_FIELD_MAX_LISTS = 4,
    ESP_GSP_FIELD_LIST_MAX_SLOTS = 5,
    ESP_GSP_FIELD_LIST_TEXT_SLOTS = 6,
    ESP_GSP_FIELD_COMPONENT_INSTANCES = 7,
    ESP_GSP_FIELD_STACK_VIEW_MAX_DEPTH = 8,
    ESP_GSP_FIELD_COMPONENT_BATCH_MAX = 9,
    ESP_GSP_FIELD_TRANSACTION_UPDATE_CAPACITY = 10,
    ESP_GSP_FIELD_RENDER_CLIP_STACK_DEPTH = 11,
    ESP_GSP_FIELD_RENDER_TILE_SPAN_CAPACITY = 12,
    ESP_GSP_FIELD_COMPONENT_OVERLAY_COMMANDS = 13,
    ESP_GSP_FIELD_DIRTY_RECT_CAPACITY = 14,
    ESP_GSP_FIELD_CANVAS_SLOTS = 15,
    ESP_GSP_FIELD_MAX_ASSET_ANIMS = 16,
    ESP_GSP_FIELD_TEXT_SLOTS = 17,
    ESP_GSP_FIELD_TEXT_CAPACITY = 18,
    ESP_GSP_FIELD_DEFAULT_DYNAMIC_IMAGE_SLOTS = 19,
    ESP_GSP_FIELD_MAX_DYNAMIC_IMAGE_TARGETS = 20,
    ESP_GSP_FIELD_MAX_FONTS_PER_SCENE = 21,
    ESP_GSP_FIELD_FREETYPE_CACHE_GLYPHS = 22,
    ESP_GSP_FIELD_FREETYPE_GLYPH_MAX_PX = 23,
    ESP_GSP_FIELD_ACCEL_MAX_DRIVERS = 24,
    ESP_GSP_FIELD_ACCEL_MAX_PENDING_BLITS = 25,
    ESP_GSP_FIELD_ACCEL_SYNC_TIMEOUT_MS = 26,
    ESP_GSP_FIELD_ACCEL_MIN_BLIT_PIXELS = 27,
    ESP_GSP_FIELD_PPA_MIN_FILL_PIXELS = 28,
    ESP_GSP_FIELD_PPA_MIN_BLEND_PIXELS = 29,
    ESP_GSP_FIELD_PPA_RUNTIME_SCALE = 30,
    ESP_GSP_FIELD_PPA_MIN_SCALE_PIXELS = 31,
    ESP_GSP_FIELD_PPA_FILL_MAX_SPAN_PIXELS = 32,
    ESP_GSP_FIELD_IMAGE_CACHE_ENTRIES = 33,
    ESP_GSP_FIELD_IMAGE_CACHE_SHORTAGE_RETRIES = 34,
    ESP_GSP_FIELD_CONTEXT_DEFAULT_GLYPH_RUNS = 35,
    ESP_GSP_FIELD_CONTEXT_DEFAULT_INSTANCES = 36,
    ESP_GSP_FIELD_INSTANCE_STATES_PER_SLOT = 37,
    ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MIN_BYTES = 38,
    ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MAX_BYTES = 39,
    ESP_GSP_FIELD_IMAGE_CACHE_HOST_DEFAULT_BYTES = 40,
    ESP_GSP_FIELD_ENABLE_IMAGE_CACHE = 41,
    ESP_GSP_FIELD_ENABLE_TRANSITION_SNAPSHOTS = 42,
    ESP_GSP_FIELD_RENDER_TASK_STACK_PSRAM = 43,
    ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE = 44,
    ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE_FREETYPE = 45,
    ESP_GSP_FIELD_RENDER_TASK_PRIORITY = 46,
    ESP_GSP_FIELD_ENABLE_ASYNC_DECODE = 47,
    ESP_GSP_FIELD_DECODE_TASK_STACK_PSRAM = 48,
    ESP_GSP_FIELD_DECODE_TASK_STACK_SIZE = 49,
    ESP_GSP_FIELD_DECODE_TASK_PRIORITY = 50,
    ESP_GSP_FIELD_DECODE_TASK_IDLE_POLL_MS = 51,
    ESP_GSP_FIELD_ANIM_FRAME_MEMORY = 52,
    ESP_GSP_FIELD_ANIM_MAX_FRAME_BYTES = 53,
    ESP_GSP_FIELD_ANIM_PATCH_RECTS = 54,
    ESP_GSP_FIELD_ANIM_REFERENCE_COMMANDS = 55,
    ESP_GSP_FIELD_ANIM_INTERNAL_FRAME_MAX_BYTES = 56,
    ESP_GSP_FIELD_QUEUE_DEPTH = 57,
    ESP_GSP_FIELD_ACTIVE_TICK_MS = 58,
    ESP_GSP_FIELD_IDLE_POLL_MS = 59,
    ESP_GSP_FIELD_POINTER_POLL_MS = 60,
    ESP_GSP_FIELD_TOUCH_RELEASE_CONFIRM_POLLS = 61,
    ESP_GSP_FIELD_SCROLL_PHYS_SAMPLES = 62,
    ESP_GSP_FIELD_SCROLL_VELOCITY_WINDOW_MS = 63,
    ESP_GSP_FIELD_SCROLL_RELEASE_GRACE_MS = 64,
    ESP_GSP_FIELD_SCROLL_STOP_SPEED_PX_S = 65,
    ESP_GSP_FIELD_SCROLL_MIN_FLING_SPEED_PX_S = 66,
    ESP_GSP_FIELD_SCROLL_MAX_RELEASE_SPEED_PX_S = 67,
    ESP_GSP_FIELD_SCROLL_DECAY_MS = 68,
    ESP_GSP_FIELD_SCROLL_MAX_TICK_MS = 69,
    ESP_GSP_FIELD_SCROLL_SNAP_RESPONSE_MS = 70,
    ESP_GSP_FIELD_SWIPE_KINETICS_SAMPLES = 71,
    ESP_GSP_FIELD_SWIPE_VELOCITY_WINDOW_MS = 72,
    ESP_GSP_FIELD_SWIPE_RELEASE_GRACE_MS = 73,
    ESP_GSP_FIELD_SWIPE_SETTLE_MIN_MS = 74,
    ESP_GSP_FIELD_SWIPE_SETTLE_BASE_MS = 75,
    ESP_GSP_FIELD_SWIPE_SETTLE_DISTANCE_MS = 76,
    ESP_GSP_FIELD_SWIPE_SETTLE_MAX_MS = 77,
    ESP_GSP_FIELD_SWIPE_SETTLE_SPEED_REDUCTION_MS = 78,
    ESP_GSP_FIELD_SWIPE_SETTLE_MAX_SPEED_REDUCTION_MS = 79,
    ESP_GSP_FIELD_PAGE_FLOW_SETTLE_MS = 80,
    ESP_GSP_FIELD_STACK_VIEW_SETTLE_MS = 81,
    ESP_GSP_FIELD_DRAWER_SETTLE_MS = 82,
    ESP_GSP_FIELD_BOOLEAN_TWEEN_MS = 83,
    ESP_GSP_FIELD_MAX_TOUCH_POINTS = 84,
    ESP_GSP_FIELD_TAP_SLOP_PX = 85,
    ESP_GSP_FIELD_DRAG_START_PX = 86,
    ESP_GSP_FIELD_SWIPE_FLICK_PX = 87,
    ESP_GSP_FIELD_SCENE_SWIPE_MIN_FLING_PX = 88,
    ESP_GSP_FIELD_COMPONENT_SWIPE_COMMIT_DIVISOR = 89,
    ESP_GSP_FIELD_SCENE_SWIPE_COMMIT_DIVISOR = 90,
    ESP_GSP_FIELD_SWIPE_VELOCITY_NUMERATOR = 91,
    ESP_GSP_FIELD_SWIPE_VELOCITY_DENOMINATOR = 92,
    ESP_GSP_FIELD_DRAWER_EDGE_SLOP_PX = 93,
} esp_gsp_config_field_id_t;

typedef enum {
    ESP_GSP_CONFIG_KIND_BUILD_CAPABILITY = 0,
    ESP_GSP_CONFIG_KIND_RUNTIME_POLICY = 1,
    ESP_GSP_CONFIG_KIND_RUNTIME_CAPACITY = 2,
} esp_gsp_config_kind_t;

typedef enum {
    ESP_GSP_CONFIG_SCOPE_BUILD = 0,
    ESP_GSP_CONFIG_SCOPE_PROCESS,
    ESP_GSP_CONFIG_SCOPE_PLATFORM,
    ESP_GSP_CONFIG_SCOPE_INSTANCE,
} esp_gsp_config_scope_t;

typedef enum {
    ESP_GSP_CONFIG_REQUIREMENT_NONE = 0,
    ESP_GSP_CONFIG_REQUIREMENT_FLOOR,
    ESP_GSP_CONFIG_REQUIREMENT_RAISE,
} esp_gsp_config_requirement_role_t;

typedef struct {
    const char *name;
    esp_gsp_config_kind_t kind;
    esp_gsp_config_scope_t scope;
    esp_gsp_config_requirement_role_t requirement_role;
    bool auto_value;
    bool overrideable;
    uint32_t minimum;
    uint32_t maximum;
} esp_gsp_config_desc_t;

typedef struct {
    uint32_t accel_sync_timeout_ms;
    uint32_t accel_min_blit_pixels;
    uint32_t ppa_min_fill_pixels;
    uint32_t ppa_min_blend_pixels;
    uint32_t ppa_runtime_scale;
    uint32_t ppa_min_scale_pixels;
    uint32_t ppa_fill_max_span_pixels;
    uint32_t image_cache_shortage_retries;
    uint32_t image_cache_auto_min_bytes;
    uint32_t image_cache_auto_max_bytes;
    uint32_t image_cache_host_default_bytes;
    uint32_t enable_image_cache;
    uint32_t enable_transition_snapshots;
    uint32_t render_task_stack_psram;
    uint32_t render_task_stack_size;
    uint32_t render_task_stack_size_freetype;
    uint32_t render_task_priority;
    uint32_t enable_async_decode;
    uint32_t decode_task_stack_psram;
    uint32_t decode_task_stack_size;
    uint32_t decode_task_priority;
    uint32_t decode_task_idle_poll_ms;
    uint32_t anim_frame_memory;
    uint32_t anim_max_frame_bytes;
    uint32_t anim_internal_frame_max_bytes;
    uint32_t active_tick_ms;
    uint32_t idle_poll_ms;
    uint32_t pointer_poll_ms;
    uint32_t touch_release_confirm_polls;
    uint32_t scroll_velocity_window_ms;
    uint32_t scroll_release_grace_ms;
    uint32_t scroll_stop_speed_px_s;
    uint32_t scroll_min_fling_speed_px_s;
    uint32_t scroll_max_release_speed_px_s;
    uint32_t scroll_decay_ms;
    uint32_t scroll_max_tick_ms;
    uint32_t scroll_snap_response_ms;
    uint32_t swipe_velocity_window_ms;
    uint32_t swipe_release_grace_ms;
    uint32_t swipe_settle_min_ms;
    uint32_t swipe_settle_base_ms;
    uint32_t swipe_settle_distance_ms;
    uint32_t swipe_settle_max_ms;
    uint32_t swipe_settle_speed_reduction_ms;
    uint32_t swipe_settle_max_speed_reduction_ms;
    uint32_t page_flow_settle_ms;
    uint32_t stack_view_settle_ms;
    uint32_t drawer_settle_ms;
    uint32_t boolean_tween_ms;
    uint32_t tap_slop_px;
    uint32_t drag_start_px;
    uint32_t swipe_flick_px;
    uint32_t scene_swipe_min_fling_px;
    uint32_t component_swipe_commit_divisor;
    uint32_t scene_swipe_commit_divisor;
    uint32_t swipe_velocity_numerator;
    uint32_t swipe_velocity_denominator;
    uint32_t drawer_edge_slop_px;
} esp_gsp_policy_t;

typedef struct {
    uint32_t max_scenes;
    uint32_t max_timers;
    uint32_t max_widgets;
    uint32_t max_animations;
    uint32_t max_lists;
    uint32_t list_max_slots;
    uint32_t list_text_slots;
    uint32_t component_instances;
    uint32_t stack_view_max_depth;
    uint32_t component_overlay_commands;
    uint32_t dirty_rect_capacity;
    uint32_t canvas_slots;
    uint32_t max_asset_anims;
    uint32_t text_slots;
    uint32_t default_dynamic_image_slots;
    uint32_t freetype_cache_glyphs;
    uint32_t freetype_glyph_max_px;
    uint32_t accel_max_drivers;
    uint32_t accel_max_pending_blits;
    uint32_t image_cache_entries;
    uint32_t context_default_glyph_runs;
    uint32_t context_default_instances;
    uint32_t instance_states_per_slot;
    uint32_t queue_depth;
} esp_gsp_capacity_t;

typedef struct {
    uint32_t component_batch_max;
    uint32_t transaction_update_capacity;
    uint32_t render_clip_stack_depth;
    uint32_t render_tile_span_capacity;
    uint32_t text_capacity;
    uint32_t max_dynamic_image_targets;
    uint32_t max_fonts_per_scene;
    uint32_t anim_patch_rects;
    uint32_t anim_reference_commands;
    uint32_t scroll_phys_samples;
    uint32_t swipe_kinetics_samples;
    uint32_t max_touch_points;
} esp_gsp_build_capability_t;

typedef struct {
    uint32_t schema_version;
    uint16_t abi_version;
    uint16_t field_count;
    esp_gsp_policy_t policy;
    esp_gsp_capacity_t capacity;
} esp_gsp_project_config_t;

typedef struct {
    uint32_t schema_version;
    uint16_t abi_version;
    uint16_t field_count;
    esp_gsp_build_capability_t build;
    esp_gsp_capacity_t capacity_limits;
} esp_gsp_build_caps_t;

typedef struct {
    uint32_t schema_version;
    uint16_t abi_version;
    uint16_t field_count;
    esp_gsp_policy_t policy;
    esp_gsp_capacity_t capacity;
} esp_gsp_effective_config_t;

#if defined(__cplusplus)
static_assert(sizeof(esp_gsp_capacity_t) <= 128,
              "per-instance capacity ABI exceeds 128 bytes");
#else
_Static_assert(sizeof(esp_gsp_capacity_t) <= 128,
               "per-instance capacity ABI exceeds 128 bytes");
#endif

typedef struct {
    uint16_t field_id;
    uint16_t reserved;
    uint32_t value;
} esp_gsp_config_override_entry_t;

typedef struct {
    uint16_t inline_count;
    uint16_t external_count;
    esp_gsp_config_override_entry_t entries[ESP_GSP_CONFIG_INLINE_OVERRIDES];
    const esp_gsp_config_override_entry_t *external_entries;
} esp_gsp_config_overrides_t;

typedef enum {
    ESP_GSP_CONFIG_SET_OK = 0,
    ESP_GSP_CONFIG_SET_INLINE_FULL,
    ESP_GSP_CONFIG_SET_INVALID_FIELD,
    ESP_GSP_CONFIG_SET_INVALID_VALUE,
    ESP_GSP_CONFIG_SET_INVALID_TABLE,
} esp_gsp_config_set_result_t;

const esp_gsp_project_config_t *esp_gsp_project_config(void);
const esp_gsp_build_caps_t *esp_gsp_build_caps(void);
const esp_gsp_config_desc_t *esp_gsp_config_desc(
    esp_gsp_config_field_id_t field);

static inline esp_gsp_config_set_result_t esp_gsp_config_override_set(
        esp_gsp_config_overrides_t *overrides,
        esp_gsp_config_field_id_t field, uint64_t value)
{
    if (overrides == NULL || (unsigned)field >= ESP_GSP_CONFIG_FIELD_COUNT ||
            value > UINT32_MAX) {
        return ESP_GSP_CONFIG_SET_INVALID_FIELD;
    }
    const esp_gsp_config_desc_t *desc = esp_gsp_config_desc(field);
    if (desc == NULL || !desc->overrideable) {
        return ESP_GSP_CONFIG_SET_INVALID_FIELD;
    }
    if (value < desc->minimum || value > desc->maximum) {
        return ESP_GSP_CONFIG_SET_INVALID_VALUE;
    }
    for (uint16_t index = 0; index < overrides->inline_count; ++index) {
        if (overrides->entries[index].field_id == (uint16_t)field) {
            overrides->entries[index].value = (uint32_t)value;
            return ESP_GSP_CONFIG_SET_OK;
        }
    }
    if (overrides->inline_count >= ESP_GSP_CONFIG_INLINE_OVERRIDES) {
        return ESP_GSP_CONFIG_SET_INLINE_FULL;
    }
    overrides->entries[overrides->inline_count++] =
        (esp_gsp_config_override_entry_t) {
            .field_id = (uint16_t)field,
            .reserved = 0,
            .value = (uint32_t)value,
        };
    return ESP_GSP_CONFIG_SET_OK;
}

static inline esp_gsp_config_set_result_t esp_gsp_config_override_bind_external(
        esp_gsp_config_overrides_t *overrides,
        const esp_gsp_config_override_entry_t *entries, uint16_t count)
{
    if (overrides == NULL || (count != 0 && entries == NULL)) {
        return ESP_GSP_CONFIG_SET_INVALID_TABLE;
    }
    for (uint16_t index = 0; index < count; ++index) {
        const esp_gsp_config_desc_t *desc = esp_gsp_config_desc(
            (esp_gsp_config_field_id_t)entries[index].field_id);
        if (entries[index].field_id >= ESP_GSP_CONFIG_FIELD_COUNT ||
                desc == NULL || !desc->overrideable) {
            return ESP_GSP_CONFIG_SET_INVALID_FIELD;
        }
        if (entries[index].value < desc->minimum ||
                entries[index].value > desc->maximum) {
            return ESP_GSP_CONFIG_SET_INVALID_VALUE;
        }
        for (uint16_t prior = 0; prior < index; ++prior) {
            if (entries[prior].field_id == entries[index].field_id) {
                return ESP_GSP_CONFIG_SET_INVALID_TABLE;
            }
        }
        for (uint16_t prior = 0; prior < overrides->inline_count; ++prior) {
            if (overrides->entries[prior].field_id ==
                    entries[index].field_id) {
                return ESP_GSP_CONFIG_SET_INVALID_TABLE;
            }
        }
    }
    overrides->external_entries = entries;
    overrides->external_count = count;
    return ESP_GSP_CONFIG_SET_OK;
}

static inline bool esp_gsp_config_override_has(
        const esp_gsp_config_overrides_t *overrides,
        esp_gsp_config_field_id_t field)
{
    if (overrides == NULL || (unsigned)field >= ESP_GSP_CONFIG_FIELD_COUNT) {
        return false;
    }
    for (uint16_t index = 0; index < overrides->inline_count; ++index) {
        if (overrides->entries[index].field_id == (uint16_t)field) {
            return true;
        }
    }
    for (uint16_t index = 0; index < overrides->external_count; ++index) {
        if (overrides->external_entries[index].field_id == (uint16_t)field) {
            return true;
        }
    }
    return false;
}

static inline uint32_t esp_gsp_config_override_value(
        const esp_gsp_config_overrides_t *overrides,
        esp_gsp_config_field_id_t field)
{
    if (overrides != NULL) {
        for (uint16_t index = 0; index < overrides->inline_count; ++index) {
            if (overrides->entries[index].field_id == (uint16_t)field) {
                return overrides->entries[index].value;
            }
        }
        for (uint16_t index = 0; index < overrides->external_count; ++index) {
            if (overrides->external_entries[index].field_id ==
                    (uint16_t)field) {
                return overrides->external_entries[index].value;
            }
        }
    }
    return 0;
}

static inline bool esp_gsp_config_overrides_valid(
        const esp_gsp_config_overrides_t *overrides)
{
    if (overrides == NULL) {
        return true;
    }
    if (overrides->inline_count > ESP_GSP_CONFIG_INLINE_OVERRIDES ||
            (overrides->external_count != 0 &&
             overrides->external_entries == NULL)) {
        return false;
    }
    for (uint16_t index = 0; index < overrides->inline_count; ++index) {
        const esp_gsp_config_desc_t *desc = esp_gsp_config_desc(
            (esp_gsp_config_field_id_t)overrides->entries[index].field_id);
        if (overrides->entries[index].field_id >= ESP_GSP_CONFIG_FIELD_COUNT ||
                desc == NULL || !desc->overrideable ||
                overrides->entries[index].value < desc->minimum ||
                overrides->entries[index].value > desc->maximum) {
            return false;
        }
        for (uint16_t prior = 0; prior < index; ++prior) {
            if (overrides->entries[prior].field_id ==
                    overrides->entries[index].field_id) return false;
        }
    }
    for (uint16_t index = 0; index < overrides->external_count; ++index) {
        const esp_gsp_config_desc_t *desc = esp_gsp_config_desc(
            (esp_gsp_config_field_id_t)
                overrides->external_entries[index].field_id);
        if (overrides->external_entries[index].field_id >=
                ESP_GSP_CONFIG_FIELD_COUNT || desc == NULL ||
                !desc->overrideable ||
                overrides->external_entries[index].value < desc->minimum ||
                overrides->external_entries[index].value > desc->maximum) {
            return false;
        }
        for (uint16_t prior = 0; prior < index; ++prior) {
            if (overrides->external_entries[prior].field_id ==
                    overrides->external_entries[index].field_id) return false;
        }
        for (uint16_t prior = 0; prior < overrides->inline_count; ++prior) {
            if (overrides->entries[prior].field_id ==
                    overrides->external_entries[index].field_id) return false;
        }
    }
    return true;
}

static inline uint64_t esp_gsp_config_value(
        const esp_gsp_effective_config_t *config,
        esp_gsp_config_field_id_t field)
{
    if (config == NULL || (unsigned)field >= config->field_count) {
        return 0;
    }
    switch (field) {
    case ESP_GSP_FIELD_ACCEL_SYNC_TIMEOUT_MS: return config->policy.accel_sync_timeout_ms;
    case ESP_GSP_FIELD_ACCEL_MIN_BLIT_PIXELS: return config->policy.accel_min_blit_pixels;
    case ESP_GSP_FIELD_PPA_MIN_FILL_PIXELS: return config->policy.ppa_min_fill_pixels;
    case ESP_GSP_FIELD_PPA_MIN_BLEND_PIXELS: return config->policy.ppa_min_blend_pixels;
    case ESP_GSP_FIELD_PPA_RUNTIME_SCALE: return config->policy.ppa_runtime_scale;
    case ESP_GSP_FIELD_PPA_MIN_SCALE_PIXELS: return config->policy.ppa_min_scale_pixels;
    case ESP_GSP_FIELD_PPA_FILL_MAX_SPAN_PIXELS: return config->policy.ppa_fill_max_span_pixels;
    case ESP_GSP_FIELD_IMAGE_CACHE_SHORTAGE_RETRIES: return config->policy.image_cache_shortage_retries;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MIN_BYTES: return config->policy.image_cache_auto_min_bytes;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MAX_BYTES: return config->policy.image_cache_auto_max_bytes;
    case ESP_GSP_FIELD_IMAGE_CACHE_HOST_DEFAULT_BYTES: return config->policy.image_cache_host_default_bytes;
    case ESP_GSP_FIELD_ENABLE_IMAGE_CACHE: return config->policy.enable_image_cache;
    case ESP_GSP_FIELD_ENABLE_TRANSITION_SNAPSHOTS: return config->policy.enable_transition_snapshots;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_PSRAM: return config->policy.render_task_stack_psram;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE: return config->policy.render_task_stack_size;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE_FREETYPE: return config->policy.render_task_stack_size_freetype;
    case ESP_GSP_FIELD_RENDER_TASK_PRIORITY: return config->policy.render_task_priority;
    case ESP_GSP_FIELD_ENABLE_ASYNC_DECODE: return config->policy.enable_async_decode;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_PSRAM: return config->policy.decode_task_stack_psram;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_SIZE: return config->policy.decode_task_stack_size;
    case ESP_GSP_FIELD_DECODE_TASK_PRIORITY: return config->policy.decode_task_priority;
    case ESP_GSP_FIELD_DECODE_TASK_IDLE_POLL_MS: return config->policy.decode_task_idle_poll_ms;
    case ESP_GSP_FIELD_ANIM_FRAME_MEMORY: return config->policy.anim_frame_memory;
    case ESP_GSP_FIELD_ANIM_MAX_FRAME_BYTES: return config->policy.anim_max_frame_bytes;
    case ESP_GSP_FIELD_ANIM_INTERNAL_FRAME_MAX_BYTES: return config->policy.anim_internal_frame_max_bytes;
    case ESP_GSP_FIELD_ACTIVE_TICK_MS: return config->policy.active_tick_ms;
    case ESP_GSP_FIELD_IDLE_POLL_MS: return config->policy.idle_poll_ms;
    case ESP_GSP_FIELD_POINTER_POLL_MS: return config->policy.pointer_poll_ms;
    case ESP_GSP_FIELD_TOUCH_RELEASE_CONFIRM_POLLS: return config->policy.touch_release_confirm_polls;
    case ESP_GSP_FIELD_SCROLL_VELOCITY_WINDOW_MS: return config->policy.scroll_velocity_window_ms;
    case ESP_GSP_FIELD_SCROLL_RELEASE_GRACE_MS: return config->policy.scroll_release_grace_ms;
    case ESP_GSP_FIELD_SCROLL_STOP_SPEED_PX_S: return config->policy.scroll_stop_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_MIN_FLING_SPEED_PX_S: return config->policy.scroll_min_fling_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_MAX_RELEASE_SPEED_PX_S: return config->policy.scroll_max_release_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_DECAY_MS: return config->policy.scroll_decay_ms;
    case ESP_GSP_FIELD_SCROLL_MAX_TICK_MS: return config->policy.scroll_max_tick_ms;
    case ESP_GSP_FIELD_SCROLL_SNAP_RESPONSE_MS: return config->policy.scroll_snap_response_ms;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_WINDOW_MS: return config->policy.swipe_velocity_window_ms;
    case ESP_GSP_FIELD_SWIPE_RELEASE_GRACE_MS: return config->policy.swipe_release_grace_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MIN_MS: return config->policy.swipe_settle_min_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_BASE_MS: return config->policy.swipe_settle_base_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_DISTANCE_MS: return config->policy.swipe_settle_distance_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_MS: return config->policy.swipe_settle_max_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_SPEED_REDUCTION_MS: return config->policy.swipe_settle_speed_reduction_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_SPEED_REDUCTION_MS: return config->policy.swipe_settle_max_speed_reduction_ms;
    case ESP_GSP_FIELD_PAGE_FLOW_SETTLE_MS: return config->policy.page_flow_settle_ms;
    case ESP_GSP_FIELD_STACK_VIEW_SETTLE_MS: return config->policy.stack_view_settle_ms;
    case ESP_GSP_FIELD_DRAWER_SETTLE_MS: return config->policy.drawer_settle_ms;
    case ESP_GSP_FIELD_BOOLEAN_TWEEN_MS: return config->policy.boolean_tween_ms;
    case ESP_GSP_FIELD_TAP_SLOP_PX: return config->policy.tap_slop_px;
    case ESP_GSP_FIELD_DRAG_START_PX: return config->policy.drag_start_px;
    case ESP_GSP_FIELD_SWIPE_FLICK_PX: return config->policy.swipe_flick_px;
    case ESP_GSP_FIELD_SCENE_SWIPE_MIN_FLING_PX: return config->policy.scene_swipe_min_fling_px;
    case ESP_GSP_FIELD_COMPONENT_SWIPE_COMMIT_DIVISOR: return config->policy.component_swipe_commit_divisor;
    case ESP_GSP_FIELD_SCENE_SWIPE_COMMIT_DIVISOR: return config->policy.scene_swipe_commit_divisor;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_NUMERATOR: return config->policy.swipe_velocity_numerator;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_DENOMINATOR: return config->policy.swipe_velocity_denominator;
    case ESP_GSP_FIELD_DRAWER_EDGE_SLOP_PX: return config->policy.drawer_edge_slop_px;
    case ESP_GSP_FIELD_MAX_SCENES: return config->capacity.max_scenes;
    case ESP_GSP_FIELD_MAX_TIMERS: return config->capacity.max_timers;
    case ESP_GSP_FIELD_MAX_WIDGETS: return config->capacity.max_widgets;
    case ESP_GSP_FIELD_MAX_ANIMATIONS: return config->capacity.max_animations;
    case ESP_GSP_FIELD_MAX_LISTS: return config->capacity.max_lists;
    case ESP_GSP_FIELD_LIST_MAX_SLOTS: return config->capacity.list_max_slots;
    case ESP_GSP_FIELD_LIST_TEXT_SLOTS: return config->capacity.list_text_slots;
    case ESP_GSP_FIELD_COMPONENT_INSTANCES: return config->capacity.component_instances;
    case ESP_GSP_FIELD_STACK_VIEW_MAX_DEPTH: return config->capacity.stack_view_max_depth;
    case ESP_GSP_FIELD_COMPONENT_OVERLAY_COMMANDS: return config->capacity.component_overlay_commands;
    case ESP_GSP_FIELD_DIRTY_RECT_CAPACITY: return config->capacity.dirty_rect_capacity;
    case ESP_GSP_FIELD_CANVAS_SLOTS: return config->capacity.canvas_slots;
    case ESP_GSP_FIELD_MAX_ASSET_ANIMS: return config->capacity.max_asset_anims;
    case ESP_GSP_FIELD_TEXT_SLOTS: return config->capacity.text_slots;
    case ESP_GSP_FIELD_DEFAULT_DYNAMIC_IMAGE_SLOTS: return config->capacity.default_dynamic_image_slots;
    case ESP_GSP_FIELD_FREETYPE_CACHE_GLYPHS: return config->capacity.freetype_cache_glyphs;
    case ESP_GSP_FIELD_FREETYPE_GLYPH_MAX_PX: return config->capacity.freetype_glyph_max_px;
    case ESP_GSP_FIELD_ACCEL_MAX_DRIVERS: return config->capacity.accel_max_drivers;
    case ESP_GSP_FIELD_ACCEL_MAX_PENDING_BLITS: return config->capacity.accel_max_pending_blits;
    case ESP_GSP_FIELD_IMAGE_CACHE_ENTRIES: return config->capacity.image_cache_entries;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_GLYPH_RUNS: return config->capacity.context_default_glyph_runs;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_INSTANCES: return config->capacity.context_default_instances;
    case ESP_GSP_FIELD_INSTANCE_STATES_PER_SLOT: return config->capacity.instance_states_per_slot;
    case ESP_GSP_FIELD_QUEUE_DEPTH: return config->capacity.queue_depth;
    default: return 0;
    }
}

static inline uint64_t esp_gsp_project_config_value(
        const esp_gsp_project_config_t *config,
        esp_gsp_config_field_id_t field)
{
    if (config == NULL || (unsigned)field >= config->field_count) {
        return 0;
    }
    switch (field) {
    case ESP_GSP_FIELD_ACCEL_SYNC_TIMEOUT_MS: return config->policy.accel_sync_timeout_ms;
    case ESP_GSP_FIELD_ACCEL_MIN_BLIT_PIXELS: return config->policy.accel_min_blit_pixels;
    case ESP_GSP_FIELD_PPA_MIN_FILL_PIXELS: return config->policy.ppa_min_fill_pixels;
    case ESP_GSP_FIELD_PPA_MIN_BLEND_PIXELS: return config->policy.ppa_min_blend_pixels;
    case ESP_GSP_FIELD_PPA_RUNTIME_SCALE: return config->policy.ppa_runtime_scale;
    case ESP_GSP_FIELD_PPA_MIN_SCALE_PIXELS: return config->policy.ppa_min_scale_pixels;
    case ESP_GSP_FIELD_PPA_FILL_MAX_SPAN_PIXELS: return config->policy.ppa_fill_max_span_pixels;
    case ESP_GSP_FIELD_IMAGE_CACHE_SHORTAGE_RETRIES: return config->policy.image_cache_shortage_retries;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MIN_BYTES: return config->policy.image_cache_auto_min_bytes;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MAX_BYTES: return config->policy.image_cache_auto_max_bytes;
    case ESP_GSP_FIELD_IMAGE_CACHE_HOST_DEFAULT_BYTES: return config->policy.image_cache_host_default_bytes;
    case ESP_GSP_FIELD_ENABLE_IMAGE_CACHE: return config->policy.enable_image_cache;
    case ESP_GSP_FIELD_ENABLE_TRANSITION_SNAPSHOTS: return config->policy.enable_transition_snapshots;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_PSRAM: return config->policy.render_task_stack_psram;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE: return config->policy.render_task_stack_size;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE_FREETYPE: return config->policy.render_task_stack_size_freetype;
    case ESP_GSP_FIELD_RENDER_TASK_PRIORITY: return config->policy.render_task_priority;
    case ESP_GSP_FIELD_ENABLE_ASYNC_DECODE: return config->policy.enable_async_decode;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_PSRAM: return config->policy.decode_task_stack_psram;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_SIZE: return config->policy.decode_task_stack_size;
    case ESP_GSP_FIELD_DECODE_TASK_PRIORITY: return config->policy.decode_task_priority;
    case ESP_GSP_FIELD_DECODE_TASK_IDLE_POLL_MS: return config->policy.decode_task_idle_poll_ms;
    case ESP_GSP_FIELD_ANIM_FRAME_MEMORY: return config->policy.anim_frame_memory;
    case ESP_GSP_FIELD_ANIM_MAX_FRAME_BYTES: return config->policy.anim_max_frame_bytes;
    case ESP_GSP_FIELD_ANIM_INTERNAL_FRAME_MAX_BYTES: return config->policy.anim_internal_frame_max_bytes;
    case ESP_GSP_FIELD_ACTIVE_TICK_MS: return config->policy.active_tick_ms;
    case ESP_GSP_FIELD_IDLE_POLL_MS: return config->policy.idle_poll_ms;
    case ESP_GSP_FIELD_POINTER_POLL_MS: return config->policy.pointer_poll_ms;
    case ESP_GSP_FIELD_TOUCH_RELEASE_CONFIRM_POLLS: return config->policy.touch_release_confirm_polls;
    case ESP_GSP_FIELD_SCROLL_VELOCITY_WINDOW_MS: return config->policy.scroll_velocity_window_ms;
    case ESP_GSP_FIELD_SCROLL_RELEASE_GRACE_MS: return config->policy.scroll_release_grace_ms;
    case ESP_GSP_FIELD_SCROLL_STOP_SPEED_PX_S: return config->policy.scroll_stop_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_MIN_FLING_SPEED_PX_S: return config->policy.scroll_min_fling_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_MAX_RELEASE_SPEED_PX_S: return config->policy.scroll_max_release_speed_px_s;
    case ESP_GSP_FIELD_SCROLL_DECAY_MS: return config->policy.scroll_decay_ms;
    case ESP_GSP_FIELD_SCROLL_MAX_TICK_MS: return config->policy.scroll_max_tick_ms;
    case ESP_GSP_FIELD_SCROLL_SNAP_RESPONSE_MS: return config->policy.scroll_snap_response_ms;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_WINDOW_MS: return config->policy.swipe_velocity_window_ms;
    case ESP_GSP_FIELD_SWIPE_RELEASE_GRACE_MS: return config->policy.swipe_release_grace_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MIN_MS: return config->policy.swipe_settle_min_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_BASE_MS: return config->policy.swipe_settle_base_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_DISTANCE_MS: return config->policy.swipe_settle_distance_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_MS: return config->policy.swipe_settle_max_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_SPEED_REDUCTION_MS: return config->policy.swipe_settle_speed_reduction_ms;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_SPEED_REDUCTION_MS: return config->policy.swipe_settle_max_speed_reduction_ms;
    case ESP_GSP_FIELD_PAGE_FLOW_SETTLE_MS: return config->policy.page_flow_settle_ms;
    case ESP_GSP_FIELD_STACK_VIEW_SETTLE_MS: return config->policy.stack_view_settle_ms;
    case ESP_GSP_FIELD_DRAWER_SETTLE_MS: return config->policy.drawer_settle_ms;
    case ESP_GSP_FIELD_BOOLEAN_TWEEN_MS: return config->policy.boolean_tween_ms;
    case ESP_GSP_FIELD_TAP_SLOP_PX: return config->policy.tap_slop_px;
    case ESP_GSP_FIELD_DRAG_START_PX: return config->policy.drag_start_px;
    case ESP_GSP_FIELD_SWIPE_FLICK_PX: return config->policy.swipe_flick_px;
    case ESP_GSP_FIELD_SCENE_SWIPE_MIN_FLING_PX: return config->policy.scene_swipe_min_fling_px;
    case ESP_GSP_FIELD_COMPONENT_SWIPE_COMMIT_DIVISOR: return config->policy.component_swipe_commit_divisor;
    case ESP_GSP_FIELD_SCENE_SWIPE_COMMIT_DIVISOR: return config->policy.scene_swipe_commit_divisor;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_NUMERATOR: return config->policy.swipe_velocity_numerator;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_DENOMINATOR: return config->policy.swipe_velocity_denominator;
    case ESP_GSP_FIELD_DRAWER_EDGE_SLOP_PX: return config->policy.drawer_edge_slop_px;
    case ESP_GSP_FIELD_MAX_SCENES: return config->capacity.max_scenes;
    case ESP_GSP_FIELD_MAX_TIMERS: return config->capacity.max_timers;
    case ESP_GSP_FIELD_MAX_WIDGETS: return config->capacity.max_widgets;
    case ESP_GSP_FIELD_MAX_ANIMATIONS: return config->capacity.max_animations;
    case ESP_GSP_FIELD_MAX_LISTS: return config->capacity.max_lists;
    case ESP_GSP_FIELD_LIST_MAX_SLOTS: return config->capacity.list_max_slots;
    case ESP_GSP_FIELD_LIST_TEXT_SLOTS: return config->capacity.list_text_slots;
    case ESP_GSP_FIELD_COMPONENT_INSTANCES: return config->capacity.component_instances;
    case ESP_GSP_FIELD_STACK_VIEW_MAX_DEPTH: return config->capacity.stack_view_max_depth;
    case ESP_GSP_FIELD_COMPONENT_OVERLAY_COMMANDS: return config->capacity.component_overlay_commands;
    case ESP_GSP_FIELD_DIRTY_RECT_CAPACITY: return config->capacity.dirty_rect_capacity;
    case ESP_GSP_FIELD_CANVAS_SLOTS: return config->capacity.canvas_slots;
    case ESP_GSP_FIELD_MAX_ASSET_ANIMS: return config->capacity.max_asset_anims;
    case ESP_GSP_FIELD_TEXT_SLOTS: return config->capacity.text_slots;
    case ESP_GSP_FIELD_DEFAULT_DYNAMIC_IMAGE_SLOTS: return config->capacity.default_dynamic_image_slots;
    case ESP_GSP_FIELD_FREETYPE_CACHE_GLYPHS: return config->capacity.freetype_cache_glyphs;
    case ESP_GSP_FIELD_FREETYPE_GLYPH_MAX_PX: return config->capacity.freetype_glyph_max_px;
    case ESP_GSP_FIELD_ACCEL_MAX_DRIVERS: return config->capacity.accel_max_drivers;
    case ESP_GSP_FIELD_ACCEL_MAX_PENDING_BLITS: return config->capacity.accel_max_pending_blits;
    case ESP_GSP_FIELD_IMAGE_CACHE_ENTRIES: return config->capacity.image_cache_entries;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_GLYPH_RUNS: return config->capacity.context_default_glyph_runs;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_INSTANCES: return config->capacity.context_default_instances;
    case ESP_GSP_FIELD_INSTANCE_STATES_PER_SLOT: return config->capacity.instance_states_per_slot;
    case ESP_GSP_FIELD_QUEUE_DEPTH: return config->capacity.queue_depth;
    default: return 0;
    }
}

static inline uint64_t esp_gsp_build_cap_value(
        const esp_gsp_build_caps_t *caps,
        esp_gsp_config_field_id_t field)
{
    if (caps == NULL || (unsigned)field >= caps->field_count) {
        return 0;
    }
    switch (field) {
    case ESP_GSP_FIELD_COMPONENT_BATCH_MAX: return caps->build.component_batch_max;
    case ESP_GSP_FIELD_TRANSACTION_UPDATE_CAPACITY: return caps->build.transaction_update_capacity;
    case ESP_GSP_FIELD_RENDER_CLIP_STACK_DEPTH: return caps->build.render_clip_stack_depth;
    case ESP_GSP_FIELD_RENDER_TILE_SPAN_CAPACITY: return caps->build.render_tile_span_capacity;
    case ESP_GSP_FIELD_TEXT_CAPACITY: return caps->build.text_capacity;
    case ESP_GSP_FIELD_MAX_DYNAMIC_IMAGE_TARGETS: return caps->build.max_dynamic_image_targets;
    case ESP_GSP_FIELD_MAX_FONTS_PER_SCENE: return caps->build.max_fonts_per_scene;
    case ESP_GSP_FIELD_ANIM_PATCH_RECTS: return caps->build.anim_patch_rects;
    case ESP_GSP_FIELD_ANIM_REFERENCE_COMMANDS: return caps->build.anim_reference_commands;
    case ESP_GSP_FIELD_SCROLL_PHYS_SAMPLES: return caps->build.scroll_phys_samples;
    case ESP_GSP_FIELD_SWIPE_KINETICS_SAMPLES: return caps->build.swipe_kinetics_samples;
    case ESP_GSP_FIELD_MAX_TOUCH_POINTS: return caps->build.max_touch_points;
    case ESP_GSP_FIELD_MAX_SCENES: return caps->capacity_limits.max_scenes;
    case ESP_GSP_FIELD_MAX_TIMERS: return caps->capacity_limits.max_timers;
    case ESP_GSP_FIELD_MAX_WIDGETS: return caps->capacity_limits.max_widgets;
    case ESP_GSP_FIELD_MAX_ANIMATIONS: return caps->capacity_limits.max_animations;
    case ESP_GSP_FIELD_MAX_LISTS: return caps->capacity_limits.max_lists;
    case ESP_GSP_FIELD_LIST_MAX_SLOTS: return caps->capacity_limits.list_max_slots;
    case ESP_GSP_FIELD_LIST_TEXT_SLOTS: return caps->capacity_limits.list_text_slots;
    case ESP_GSP_FIELD_COMPONENT_INSTANCES: return caps->capacity_limits.component_instances;
    case ESP_GSP_FIELD_STACK_VIEW_MAX_DEPTH: return caps->capacity_limits.stack_view_max_depth;
    case ESP_GSP_FIELD_COMPONENT_OVERLAY_COMMANDS: return caps->capacity_limits.component_overlay_commands;
    case ESP_GSP_FIELD_DIRTY_RECT_CAPACITY: return caps->capacity_limits.dirty_rect_capacity;
    case ESP_GSP_FIELD_CANVAS_SLOTS: return caps->capacity_limits.canvas_slots;
    case ESP_GSP_FIELD_MAX_ASSET_ANIMS: return caps->capacity_limits.max_asset_anims;
    case ESP_GSP_FIELD_TEXT_SLOTS: return caps->capacity_limits.text_slots;
    case ESP_GSP_FIELD_DEFAULT_DYNAMIC_IMAGE_SLOTS: return caps->capacity_limits.default_dynamic_image_slots;
    case ESP_GSP_FIELD_FREETYPE_CACHE_GLYPHS: return caps->capacity_limits.freetype_cache_glyphs;
    case ESP_GSP_FIELD_FREETYPE_GLYPH_MAX_PX: return caps->capacity_limits.freetype_glyph_max_px;
    case ESP_GSP_FIELD_ACCEL_MAX_DRIVERS: return caps->capacity_limits.accel_max_drivers;
    case ESP_GSP_FIELD_ACCEL_MAX_PENDING_BLITS: return caps->capacity_limits.accel_max_pending_blits;
    case ESP_GSP_FIELD_IMAGE_CACHE_ENTRIES: return caps->capacity_limits.image_cache_entries;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_GLYPH_RUNS: return caps->capacity_limits.context_default_glyph_runs;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_INSTANCES: return caps->capacity_limits.context_default_instances;
    case ESP_GSP_FIELD_INSTANCE_STATES_PER_SLOT: return caps->capacity_limits.instance_states_per_slot;
    case ESP_GSP_FIELD_QUEUE_DEPTH: return caps->capacity_limits.queue_depth;
    default: return 0;
    }
}

static inline bool esp_gsp_effective_config_set(
        esp_gsp_effective_config_t *config,
        esp_gsp_config_field_id_t field, uint32_t value)
{
    if (config == NULL || (unsigned)field >= config->field_count) {
        return false;
    }
    switch (field) {
    case ESP_GSP_FIELD_ACCEL_SYNC_TIMEOUT_MS: config->policy.accel_sync_timeout_ms = value; return true;
    case ESP_GSP_FIELD_ACCEL_MIN_BLIT_PIXELS: config->policy.accel_min_blit_pixels = value; return true;
    case ESP_GSP_FIELD_PPA_MIN_FILL_PIXELS: config->policy.ppa_min_fill_pixels = value; return true;
    case ESP_GSP_FIELD_PPA_MIN_BLEND_PIXELS: config->policy.ppa_min_blend_pixels = value; return true;
    case ESP_GSP_FIELD_PPA_RUNTIME_SCALE: config->policy.ppa_runtime_scale = value; return true;
    case ESP_GSP_FIELD_PPA_MIN_SCALE_PIXELS: config->policy.ppa_min_scale_pixels = value; return true;
    case ESP_GSP_FIELD_PPA_FILL_MAX_SPAN_PIXELS: config->policy.ppa_fill_max_span_pixels = value; return true;
    case ESP_GSP_FIELD_IMAGE_CACHE_SHORTAGE_RETRIES: config->policy.image_cache_shortage_retries = value; return true;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MIN_BYTES: config->policy.image_cache_auto_min_bytes = value; return true;
    case ESP_GSP_FIELD_IMAGE_CACHE_AUTO_MAX_BYTES: config->policy.image_cache_auto_max_bytes = value; return true;
    case ESP_GSP_FIELD_IMAGE_CACHE_HOST_DEFAULT_BYTES: config->policy.image_cache_host_default_bytes = value; return true;
    case ESP_GSP_FIELD_ENABLE_IMAGE_CACHE: config->policy.enable_image_cache = value; return true;
    case ESP_GSP_FIELD_ENABLE_TRANSITION_SNAPSHOTS: config->policy.enable_transition_snapshots = value; return true;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_PSRAM: config->policy.render_task_stack_psram = value; return true;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE: config->policy.render_task_stack_size = value; return true;
    case ESP_GSP_FIELD_RENDER_TASK_STACK_SIZE_FREETYPE: config->policy.render_task_stack_size_freetype = value; return true;
    case ESP_GSP_FIELD_RENDER_TASK_PRIORITY: config->policy.render_task_priority = value; return true;
    case ESP_GSP_FIELD_ENABLE_ASYNC_DECODE: config->policy.enable_async_decode = value; return true;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_PSRAM: config->policy.decode_task_stack_psram = value; return true;
    case ESP_GSP_FIELD_DECODE_TASK_STACK_SIZE: config->policy.decode_task_stack_size = value; return true;
    case ESP_GSP_FIELD_DECODE_TASK_PRIORITY: config->policy.decode_task_priority = value; return true;
    case ESP_GSP_FIELD_DECODE_TASK_IDLE_POLL_MS: config->policy.decode_task_idle_poll_ms = value; return true;
    case ESP_GSP_FIELD_ANIM_FRAME_MEMORY: config->policy.anim_frame_memory = value; return true;
    case ESP_GSP_FIELD_ANIM_MAX_FRAME_BYTES: config->policy.anim_max_frame_bytes = value; return true;
    case ESP_GSP_FIELD_ANIM_INTERNAL_FRAME_MAX_BYTES: config->policy.anim_internal_frame_max_bytes = value; return true;
    case ESP_GSP_FIELD_ACTIVE_TICK_MS: config->policy.active_tick_ms = value; return true;
    case ESP_GSP_FIELD_IDLE_POLL_MS: config->policy.idle_poll_ms = value; return true;
    case ESP_GSP_FIELD_POINTER_POLL_MS: config->policy.pointer_poll_ms = value; return true;
    case ESP_GSP_FIELD_TOUCH_RELEASE_CONFIRM_POLLS: config->policy.touch_release_confirm_polls = value; return true;
    case ESP_GSP_FIELD_SCROLL_VELOCITY_WINDOW_MS: config->policy.scroll_velocity_window_ms = value; return true;
    case ESP_GSP_FIELD_SCROLL_RELEASE_GRACE_MS: config->policy.scroll_release_grace_ms = value; return true;
    case ESP_GSP_FIELD_SCROLL_STOP_SPEED_PX_S: config->policy.scroll_stop_speed_px_s = value; return true;
    case ESP_GSP_FIELD_SCROLL_MIN_FLING_SPEED_PX_S: config->policy.scroll_min_fling_speed_px_s = value; return true;
    case ESP_GSP_FIELD_SCROLL_MAX_RELEASE_SPEED_PX_S: config->policy.scroll_max_release_speed_px_s = value; return true;
    case ESP_GSP_FIELD_SCROLL_DECAY_MS: config->policy.scroll_decay_ms = value; return true;
    case ESP_GSP_FIELD_SCROLL_MAX_TICK_MS: config->policy.scroll_max_tick_ms = value; return true;
    case ESP_GSP_FIELD_SCROLL_SNAP_RESPONSE_MS: config->policy.scroll_snap_response_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_WINDOW_MS: config->policy.swipe_velocity_window_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_RELEASE_GRACE_MS: config->policy.swipe_release_grace_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MIN_MS: config->policy.swipe_settle_min_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_BASE_MS: config->policy.swipe_settle_base_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_DISTANCE_MS: config->policy.swipe_settle_distance_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_MS: config->policy.swipe_settle_max_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_SPEED_REDUCTION_MS: config->policy.swipe_settle_speed_reduction_ms = value; return true;
    case ESP_GSP_FIELD_SWIPE_SETTLE_MAX_SPEED_REDUCTION_MS: config->policy.swipe_settle_max_speed_reduction_ms = value; return true;
    case ESP_GSP_FIELD_PAGE_FLOW_SETTLE_MS: config->policy.page_flow_settle_ms = value; return true;
    case ESP_GSP_FIELD_STACK_VIEW_SETTLE_MS: config->policy.stack_view_settle_ms = value; return true;
    case ESP_GSP_FIELD_DRAWER_SETTLE_MS: config->policy.drawer_settle_ms = value; return true;
    case ESP_GSP_FIELD_BOOLEAN_TWEEN_MS: config->policy.boolean_tween_ms = value; return true;
    case ESP_GSP_FIELD_TAP_SLOP_PX: config->policy.tap_slop_px = value; return true;
    case ESP_GSP_FIELD_DRAG_START_PX: config->policy.drag_start_px = value; return true;
    case ESP_GSP_FIELD_SWIPE_FLICK_PX: config->policy.swipe_flick_px = value; return true;
    case ESP_GSP_FIELD_SCENE_SWIPE_MIN_FLING_PX: config->policy.scene_swipe_min_fling_px = value; return true;
    case ESP_GSP_FIELD_COMPONENT_SWIPE_COMMIT_DIVISOR: config->policy.component_swipe_commit_divisor = value; return true;
    case ESP_GSP_FIELD_SCENE_SWIPE_COMMIT_DIVISOR: config->policy.scene_swipe_commit_divisor = value; return true;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_NUMERATOR: config->policy.swipe_velocity_numerator = value; return true;
    case ESP_GSP_FIELD_SWIPE_VELOCITY_DENOMINATOR: config->policy.swipe_velocity_denominator = value; return true;
    case ESP_GSP_FIELD_DRAWER_EDGE_SLOP_PX: config->policy.drawer_edge_slop_px = value; return true;
    case ESP_GSP_FIELD_MAX_SCENES: config->capacity.max_scenes = value; return true;
    case ESP_GSP_FIELD_MAX_TIMERS: config->capacity.max_timers = value; return true;
    case ESP_GSP_FIELD_MAX_WIDGETS: config->capacity.max_widgets = value; return true;
    case ESP_GSP_FIELD_MAX_ANIMATIONS: config->capacity.max_animations = value; return true;
    case ESP_GSP_FIELD_MAX_LISTS: config->capacity.max_lists = value; return true;
    case ESP_GSP_FIELD_LIST_MAX_SLOTS: config->capacity.list_max_slots = value; return true;
    case ESP_GSP_FIELD_LIST_TEXT_SLOTS: config->capacity.list_text_slots = value; return true;
    case ESP_GSP_FIELD_COMPONENT_INSTANCES: config->capacity.component_instances = value; return true;
    case ESP_GSP_FIELD_STACK_VIEW_MAX_DEPTH: config->capacity.stack_view_max_depth = value; return true;
    case ESP_GSP_FIELD_COMPONENT_OVERLAY_COMMANDS: config->capacity.component_overlay_commands = value; return true;
    case ESP_GSP_FIELD_DIRTY_RECT_CAPACITY: config->capacity.dirty_rect_capacity = value; return true;
    case ESP_GSP_FIELD_CANVAS_SLOTS: config->capacity.canvas_slots = value; return true;
    case ESP_GSP_FIELD_MAX_ASSET_ANIMS: config->capacity.max_asset_anims = value; return true;
    case ESP_GSP_FIELD_TEXT_SLOTS: config->capacity.text_slots = value; return true;
    case ESP_GSP_FIELD_DEFAULT_DYNAMIC_IMAGE_SLOTS: config->capacity.default_dynamic_image_slots = value; return true;
    case ESP_GSP_FIELD_FREETYPE_CACHE_GLYPHS: config->capacity.freetype_cache_glyphs = value; return true;
    case ESP_GSP_FIELD_FREETYPE_GLYPH_MAX_PX: config->capacity.freetype_glyph_max_px = value; return true;
    case ESP_GSP_FIELD_ACCEL_MAX_DRIVERS: config->capacity.accel_max_drivers = value; return true;
    case ESP_GSP_FIELD_ACCEL_MAX_PENDING_BLITS: config->capacity.accel_max_pending_blits = value; return true;
    case ESP_GSP_FIELD_IMAGE_CACHE_ENTRIES: config->capacity.image_cache_entries = value; return true;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_GLYPH_RUNS: config->capacity.context_default_glyph_runs = value; return true;
    case ESP_GSP_FIELD_CONTEXT_DEFAULT_INSTANCES: config->capacity.context_default_instances = value; return true;
    case ESP_GSP_FIELD_INSTANCE_STATES_PER_SLOT: config->capacity.instance_states_per_slot = value; return true;
    case ESP_GSP_FIELD_QUEUE_DEPTH: config->capacity.queue_depth = value; return true;
    default: return false;
    }
}

#ifdef __cplusplus
}
#endif
