/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
 */
#pragma once

/* Version 1: fixed-width scalar operations, never native pointers or structs.
 * Arguments/results are arrays of eight uint32_t words. Signed values use
 * their two's-complement bit pattern. Append operations; never renumber. */
#define GSP_SIM_BRIDGE_VERSION 1
enum gsp_sim_bridge_op {
    GSP_BRIDGE_GET_VALUE = 1,
    GSP_BRIDGE_GET_COLOR,
    GSP_BRIDGE_GET_VISIBLE,
    GSP_BRIDGE_GET_TOGGLE,
    GSP_BRIDGE_COMPONENT_INFO,
    GSP_BRIDGE_COMPONENT_GET_VALUE,
    GSP_BRIDGE_COMPONENT_GET_COLOR,
    GSP_BRIDGE_COMPONENT_GET_VISIBLE,
    GSP_BRIDGE_COMPONENT_GET_CHECKED,
    GSP_BRIDGE_COMPONENT_GET_ENABLED,
    GSP_BRIDGE_COMPONENT_SET_COLOR,
    GSP_BRIDGE_COMPONENT_SET_VISIBLE,
    GSP_BRIDGE_COMPONENT_SET_CHECKED,
    GSP_BRIDGE_COMPONENT_SET_ENABLED,
    GSP_BRIDGE_GET_PROPERTY,
    GSP_BRIDGE_SET_PROPERTY,
    GSP_BRIDGE_ANIMATE,
    GSP_BRIDGE_ANIMATE_COLOR,
    GSP_BRIDGE_COMPONENT_ANIMATE_VALUE,
    GSP_BRIDGE_COMPONENT_ANIMATE_VALUE_TO,
    GSP_BRIDGE_COMPONENT_ANIMATE_COLOR,
    GSP_BRIDGE_COMPONENT_ANIMATE_COLOR_TO,
    GSP_BRIDGE_ANIMATE_PROPERTY,
    GSP_BRIDGE_ANIMATE_PROPERTY_TO,
    GSP_BRIDGE_CANVAS_INFO,
    GSP_BRIDGE_COMPONENT_RESOURCE_BIND,
};
